version: 2.1

parameters:
  namespace:
    type: string
    default: usct
  playground:
    type: boolean
    default: false
  authmode:
    type: string
    default: mosip
  image:
    type: string
    default: "app/usct/dev-backend"

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  helm: circleci/helm@3.0.0

commands:
  build_and_deploy:
    parameters:
      deploy:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - helm/install_helm_client:
          version: v3.13.0
      - run:
          name: Setup env
          command: |
              echo "export IMAGE=${CONTAINER_REGISTRY}/<< pipeline.parameters.image >>:<< pipeline.git.revision >>" >> "$BASH_ENV"
      - run:
          name: Build docker image
          command: |
            ./gradlew build bootBuildImage "--imageName=$IMAGE"
      - run:
          name: Check Helm Chart
          command: |
            helm lint ./helm
      - when:
          condition: << parameters.deploy >>
          steps:
            - aws-cli/setup:
                role_arn: "${AWS_CIRCLECI_ROLE_ARN}"
                region: ${AWS_REGION}
                role_session_name: CircleCISession
                session_duration: '1800'
            - run:
                name: Push image
                command: |
                  aws ecr get-login-password | docker login --username AWS --password-stdin "${CONTAINER_REGISTRY}"
                  docker push "$IMAGE"
            - run:
                name: Update kubeconfig
                command: |
                  aws eks update-kubeconfig --name ${EKS_CLUSTER}
            - run:
                name: Deploy project
                command: |
                  helm dependency update ./helm
                  helm upgrade --install --create-namespace \
                    --namespace << pipeline.parameters.namespace >> \
                    --set-string "backend.service.authmode=<< pipeline.parameters.authmode >>" \
                    --set-string "backend.oidcKeystorePassword=${OIDC_KEYSTORE_PASSWORD}" \
                    usct ./helm

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - build_and_deploy:
          deploy: false

  build_and_deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - build_and_deploy:
          deploy: true

workflows:
  # build every commit
  "Just build":
    when:
      and:
        - equal: [ false, << pipeline.parameters.playground >> ]
        - not:
            equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build:
          context: sandbox-dev

  # build and deploy to dev commits to main
  "Build and deploy":
    when:
      and:
        - equal: [ false, << pipeline.parameters.playground >> ]
        - equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build_and_deploy:
          context: sandbox-dev

  # build and deploy to playground depending on parameter
  "Build and deploy to playground":
    when:
      and:
        - equal: [ true, << pipeline.parameters.playground >> ]
        - equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build_and_deploy:
          context: playground
