---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployment.name }}-secrets"
  namespace: "{{ $.Release.Namespace }}"
stringData:
  keystorePassword: "{{ .Values.oidcKeystorePassword }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.deployment.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.name }}"
    spec:
      containers:
        - name: "{{ .Values.deployment.containers.name }}"
          image: "{{ .Values.deployment.containers.image }}"
          imagePullPolicy: {{ .Values.deployment.containers.imagePullPolicy }}
          env:
            - name: OIDC_JWK_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.deployment.name }}-secrets"
                  key: keystorePassword
