payment_bb_emulator:
  name: "payment-bb-emulator"
  replicaCount: 1
  labels: 
    app: "payment-bb-emulator"
  template:
    labels: 
      app: "payment-bb-emulator"
  container:
    name: payment-emulator
    image: 161826879607.dkr.ecr.eu-central-1.amazonaws.com/bb/payments/emulator/plg-backend
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent
  service:
    name: "payment-bb-emulator"
    type: ClusterIP
    port: 8080
    targetPort: 8080